### ISSUE TITLE
Getting error when running script

### ISSUE THREAD

**Issue by protagonyst** [marq4/Random-Clip-Generator#1]
Hi! Thanks for sharing this. I have been looking for something like that for quite a while now.

I get the following error when I execute the script :
> ValueError: invalid literal for int() with base 10: "'"

Any idea why?

**Comment by marq4** [comment]
Hi. Sorry I never specified that I only tested the code under Linux. Now I moved to Windows and ran into the error you reported. I have fixed it locally and I will upload a new branch for Windows today. 
You are running Windows right?

**Comment by marq4** [comment]
Please download and try with the latest version and/or see the wiki/Troubleshooting.
